package com.byoskill.pretimmobilier;

import com.byoskill.pretimmobilier.ValidationStatus;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("PretImmobilierDO")
@org.kie.api.definition.type.Description("PretImmobilierDO")
public class PretImmobilierDO implements java.io.Serializable {

	@org.kie.api.definition.type.Label("conditionsFinancieres")
	private com.byoskill.pretimmobilier.ConditionsFinancieres conditionsFinancieres;

	@org.kie.api.definition.type.Label("validationStatus")
	private ValidationStatus validationStatus;

	public com.byoskill.pretimmobilier.ConditionsFinancieres getConditionsFinancieres() {
		return this.conditionsFinancieres;
	}

	public void setConditionsFinancieres(
			com.byoskill.pretimmobilier.ConditionsFinancieres conditionsFinancieres) {
		this.conditionsFinancieres = conditionsFinancieres;
	}

	public PretImmobilierDO() {
	}

	public void setValidationStatus(
			com.byoskill.pretimmobilier.ValidationStatus validationStatus) {
		this.validationStatus = validationStatus;
	}

	public PretImmobilierDO(
			com.byoskill.pretimmobilier.ConditionsFinancieres conditionsFinancieres,
			com.byoskill.pretimmobilier.ValidationStatus validationStatus) {
		this.conditionsFinancieres = conditionsFinancieres;
		this.validationStatus = validationStatus;
	}

	public com.byoskill.pretimmobilier.ValidationStatus getValidationStatus() {
		return this.validationStatus;
	}

}
